workspace "../MFHWireframes.xcworkspace"
xcodeproj "MFHWireframes/MFHWireframes.xcodeproj"

pod "MFHWireframes", :path => "../MFHWireframes.podspec"

target "MFHWireframesTests", :exclusive => true do
      pod 'Kiwi/XCTest'
end
